project:
  type: website
  output-dir: docs
  
website:
  title: "Germán D. Orbegozo-Rodríguez"
  search: false
  navbar:
    background: "#FFFF"
  site-url: https://germanorbegozo.github.io/

format:
  html:
    theme:
      - cosmo
      - brand
      - harvard.scss
    css: styles.css
    toc: true


resources:
  - google08b9ea68848866c5.html
